services:
  vm-builder-focal:
    build: ./
    image: qemu-packer-builder:latest
    privileged: true
    cpus: 4
    devices:
      - /dev/kvm
    volumes:
      - "../:/app"
      # Packer Cache for faster builds
      - "../packer_cache:/app/packer_cache"
      - "/usr/share/OVMF/OVMF_CODE.fd:/usr/share/OVMF/OVMF_CODE.fd"
    environment:
      PACKER_LOG: 1
    network_mode: host
    command:
      - make build-focal
  vm-builder-jammy:
    build: ./
    image: qemu-packer-builder:latest
    privileged: true
    cpus: 4
    devices:
      - /dev/kvm
    volumes:
      - "../:/app"
      # Packer Cache for faster builds
      - "../packer_cache:/app/packer_cache"
      - "/usr/share/OVMF/OVMF_CODE.fd:/usr/share/OVMF/OVMF_CODE.fd"
    environment:
      PACKER_LOG: 1
    network_mode: host
    command:
      - make build-jammy
  vm-builder-noble:
    build: ./
    image: qemu-packer-builder:latest
    privileged: true
    cpus: 4
    devices:
      - /dev/kvm
    volumes:
      - "../:/app"
      # Packer Cache for faster builds
      - "../packer_cache:/app/packer_cache"
      - "/usr/share/OVMF/OVMF_CODE.fd:/usr/share/OVMF/OVMF_CODE.fd"
    environment:
      PACKER_LOG: 1
    network_mode: host
    command:
      - make build-noble
